name: flutter_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed: ^2.5.2
  get_it: ^7.6.7
  injectable: ^2.3.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.8.0
  google_fonts: ^5.1.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: 

flutter:
  uses-material-design: true
  assets:
    -  assets/
